plugins:
  Essentials:
    name: "Kitten"
    description: "Kitten is a simple-to-use server core made for this server!"
    prefix: "Kitten"
    website: "https://kittenmc.net"
    version: "3.5.1-REL"
    author: "Kotlin @ MC-Market"

  ProtocolLib:
    name: "ProtocolMeme"
    description: "ProtocolMeme is a MEEM"
    prefix: "PROTOCOLMEME"
    website: "protolmeme.com"
    version: "1.0-MEME"
    authors: ["Kotlin @ MC-Market", "dakota @ MC-Market"]

  Kamikaze:
    name: "CustomCore69"
    description: "FULLY CUSTOM CORE TOTALLY!!"
    prefix: "CUSOTM COOORE"
    website: "customcore.net"
    version: "1.0-THISWONTEVENWORK"
    author: "EEEEEE"